[instruments]
clock = { instrument = "Clock" }
signal = { instrument = "SignalGenerator" }

[instruments.lockin]
instrument = "SR_830"
adapter = "pyvisa"
resource = "GPIB0::8::INSTR"

[measurements]
time = { instrument = "clock", method = "time" }
wave = { instrument = "signal", method = "sine", args = { frequency = 0.2 } }

[rack]
period = 0.2
