[experiment]
root_path = "data"

[rack]
period = 0.25

[instruments]
clock = {instrument = "clock"}
lockin = {instrument = "sr830", adapter="pyvisa", resource="GPIB0::8::INSTR"}

[measurements]
time = {instrument = "clock", method = "time"}
vx = {instrument = "lockin", method = "get_x"}
vy = {instrument = "lockin", method = "get_y"}

[data]
path = "data_sub"

[api_server]
host = "localhost"
port = 8005

[logging]
path = "logs"
console_level = "DEBUG"
gui_level = "DEBUG"
file_level = "DEBUG"
file_name = "debug.log"