
root_path = "."

[rack]
period = 0.25

[instruments]
clock = {instrument = "clock"}
lockin1 = {instrument = "sr830", method = "GPIB", address = 11}

[measurements.set_one]
time = {instrument = "clock"}

[measurements.set_two]
ijwjafpjpaw = {instrument = "clock"}

[data]
path = "."

[api_server]
host = "localhost"
port = 8005
allowed_cors_origins = ["http://localhost:3000"]

[logging]
console_level = "DEBUG"
file_level = "DEBUG"
file_name = "debug.log"