[experiment]
root_path = "data"

[rack]
period = 0.25

[instruments]
clock = {instrument = "clock"}
lockin = {instrument = "sr830", adapter="mock", resource="GPIB0::12::INSTR"}

[measurements]
timestamp = {instrument = "clock", method = "timestamp_ms"}
time = {instrument = "clock", method = "time"}
timestamp6 = {instrument = "clock", method = "timestamp_ms"}
time2 = {instrument = "clock", method = "time"}
timestamp2 = {instrument = "clock", method = "timestamp_ms"}
time3 = {instrument = "clock", method = "time"}
timestamp3 = {instrument = "clock", method = "timestamp_ms"}
time9 = {instrument = "clock", method = "time"}

[data]
path = "data_sub"

[api_server]
host = "localhost"
port = 8005

[logging]
path = "logs"
console_level = "DEBUG"
gui_level = "DEBUG"
file_level = "DEBUG"
file_name = "debug.log"