
root_path = "./data"

[rack]
period = 0.25

[instruments]
clock = {instrument = "clock"}

[measurements]
timestamp = {instrument = "clock", method = "timestamp_ms"}
time = {instrument = "clock", method = "time"}

[data]
path = "data_sub"

[api_server]
host = "localhost"
port = 8005
allowed_cors_origins = ["http://localhost:3000"]

[logging]
path = "logs"
console_level = "DEBUG"
file_level = "DEBUG"
file_name = "debug.log"