site_name: PyAquisition
nav:
  - Home: index.md
  - Basics:
      - Installation: basics/installation.md
      - Getting Started: basics/getting_started.md
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_docstring_examples: true