site_name: PyAquisition
repo_url: https://github.com/jakeayres/pyaquisition
repo_name: pyacquisition
nav:
  - Home: index.md
  - Basics:
    - Installation: basics/installation.md
    - Getting Started: basics/getting_started.md
    - Configuration: basics/configuration.md
  - Experiment:
    - Experiment: experiment/experiment.md
    - Rack: experiment/rack.md
    - Scribe: experiment/scribe.md
    - Task Manager: experiment/task_manager.md
  - Instruments:
    - Clock: instruments/clock.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
  palette:
    primary: deep purple
  features:
    - navigation.tabs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_docstring_examples: true
            modernize_annotations: true