[tool.poetry]
name = "pyacquisition"
version = "0.1.0"
description = "Python driven data acquisition"
authors = ["Jake Ayres <jake_ayres@hotmail.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
pyserial = "^3.5"
pyvisa = "^1.13.0"
pyvisa-py = "^0.7.0"
websockets = "^11.0.3"
fastapi = "^0.101.1"
uvicorn = "^0.23.2"
scipy = "^1.11.1"
pandas = "^2.0.3"
rich = "^13.5.2"
dearpygui = "^1.11.1"
aiohttp = "3.9.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-mock = "^3.6.1"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
	"asyncio: test requires asyncio",
	"software: software test, no physical hardware required",
	"hardware: requires physical hardware",
	"SR_860: requires SR860 be connected",
	"lakeshore_350: requires lakeshore 350 be connected"
]