[tool.poetry]
name = "pyacquisition"
version = "0.1.0"
description = "Python driven data acquisition"
authors = ["Jake Ayres <jake_ayres@hotmail.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-mock = "^3.6.1"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
markers = [
	"software: software test, no physical hardware required",
	"hardware: requires physical hardware",
	"SR_860: requires SR860 be connected",
]