"""Freezes an experiment into a standalone application with PyInstaller.

Used by `pyacquisition build --toml config.toml` or `pyacquisition build --py
my_experiment.py` (see `pyacquisition.__init__.main`). PyInstaller must be
installed separately, since most uses of `pyacquisition` never need it:
`uv add pyacquisition[build]`, or `uv pip install pyinstaller` in your project.

A `--toml` build has no Python of its own, so a small, fixed entry point is
generated (`_ENTRY_SCRIPT`) that loads the config from beside the built
executable and runs it. A `--py` build freezes the script itself, so that
PyInstaller's static analysis sees whatever it imports (a sibling module, a
third-party package your own instrument needs) and bundles that too. Building
our own wrapper around it, the way the TOML path does, would hide those imports
from PyInstaller and they would silently be missing from the built application.
"""

import shutil
import subprocess
from pathlib import Path

from .core.config_parser import ConfigParser

# The instrument backends that PyInstaller's static analysis cannot see, because
# they are found at runtime rather than imported directly: pyvisa's VISA backends,
# and dearpygui's bundled native module and default font.
_COLLECT_ALL = ("pyvisa", "pyvisa_py", "dearpygui")

# Files that are read rather than imported, so the analysis does not see them: the
# new GUI's page, which the API server always serves.
_COLLECT_DATA = ("pyacquisition.new_gui",)

# The entry point for a --toml build. It is the same every time: it looks for its
# configuration beside the executable, under a fixed name, whatever the original
# file was called. `build_app` copies it there after PyInstaller has run.
_ENTRY_SCRIPT = '''\
"""Generated by `pyacquisition build --toml`. Loads config.toml from beside this
executable, and runs the experiment it describes."""

import sys
from pathlib import Path

from pyacquisition import Experiment


def _app_dir() -> Path:
    """The folder the executable is in, or this script's folder when not frozen."""
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).parent


if __name__ == "__main__":
    Experiment.from_config(str(_app_dir() / "config.toml")).run()
'''


def pyinstaller_available() -> bool:
    """Whether the `pyinstaller` command can be found."""
    return shutil.which("pyinstaller") is not None


def build_app(
    *,
    toml_file: str | None = None,
    py_file: str | None = None,
    name: str | None = None,
    onefile: bool = True,
    windowed: bool = True,
    icon: str | None = None,
    out_dir: str | Path = ".",
) -> Path:
    """
    Freezes an experiment into a standalone application.

    Give exactly one of `toml_file` or `py_file`.

    Args:
        toml_file: Path to a TOML configuration. A small entry point is generated
            that loads it, so the built application needs no Python of its own.
        py_file: Path to a Python script with an `Experiment` subclass, written
            exactly as `pyacquisition run --py` expects: `MyExperiment().run()`
            under `if __name__ == "__main__":`. The script itself is frozen, so
            whatever it imports is bundled too.
        name: The name of the built application. Defaults to the file's own name.
        onefile: Build a single executable (the default). Set to `False` to build
            a folder instead, alongside a `_internal` folder of its dependencies:
            it starts faster, because a single-file build unpacks itself to a
            temporary folder on every run, but it is no longer one file to hand
            over.
        windowed: Hide the console window. `pyacquisition`'s own logging still
            goes to the log file either way. Set to `False` to keep the console,
            to see errors from a build that is not behaving as expected.
        icon: An `.ico` file for the application's icon.
        out_dir: Where the `dist` and `build` folders go. Defaults to the
            current directory.

    Returns:
        Path: The folder holding the built application: with `onefile` (the
            default), the single executable and, for a `--toml` build, its
            `config.toml`, both directly in `out_dir`. This is what to hand
            over, or copy to a lab PC.

    Raises:
        ValueError: If `toml_file` and `py_file` are not given exactly one.
        FileNotFoundError: If PyInstaller is not installed, or `py_file` does
            not exist.
        RuntimeError: If PyInstaller fails.
    """
    if bool(toml_file) == bool(py_file):
        raise ValueError("Give exactly one of `toml_file` or `py_file`.")
    if not pyinstaller_available():
        raise FileNotFoundError(
            "PyInstaller is not installed. Add it with `uv add pyacquisition[build]` "
            "(or `uv pip install pyinstaller`), then try again."
        )

    out_dir = Path(out_dir)
    work_dir = out_dir / "build" / "_pyinstaller"
    dist_dir = out_dir / "dist"

    if toml_file:
        ConfigParser.parse(toml_file)  # fails fast, before PyInstaller runs at all
        work_dir.mkdir(parents=True, exist_ok=True)
        script = work_dir / "_entry.py"
        script.write_text(_ENTRY_SCRIPT, encoding="utf-8")
        app_name = name or Path(toml_file).stem
    else:
        script = Path(py_file)
        if not script.is_file():
            raise FileNotFoundError(f"{script} not found.")
        app_name = name or script.stem

    command = [
        "pyinstaller",
        str(script),
        "--name",
        app_name,
        "--noconfirm",
        "--onefile" if onefile else "--onedir",
        "--distpath",
        str(dist_dir),
        "--workpath",
        str(work_dir),
        "--specpath",
        str(work_dir),
    ]
    if windowed:
        command.append("--windowed")
    if icon:
        command += ["--icon", str(icon)]
    for package in _COLLECT_ALL:
        command += ["--collect-all", package]
    for package in _COLLECT_DATA:
        command += ["--collect-data", package]

    result = subprocess.run(command, check=False)  # returncode is handled below
    if result.returncode != 0:
        raise RuntimeError(f"PyInstaller failed (exit code {result.returncode}).")

    # onefile: the executable is the single file dist/<name>.exe, so that is the
    # folder its config.toml joins too. onedir: it is in its own folder instead,
    # dist/<name>/, alongside the dependencies it needs.
    app_dir = dist_dir if onefile else dist_dir / app_name
    if toml_file:
        shutil.copyfile(toml_file, app_dir / "config.toml")
    return app_dir
